import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '@/components/Copyrights'
import Copyrights from '@/components/Copyrights'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className='px-5 sm:px-16 md:px-32 md:py-0.5 py-8'>
          {/* <Navbar /> */}
          {children}
          </main>
        <Copyrights />
      
        </body>
    </html>
  )
}
