import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Copyrights";
import Copyrights from "@/components/Copyrights";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {/* <main className="px-5 sm:px-16 md:px-24 md:py-0.5 py-8"> */}
          <main className="px-0">

            <Navbar />
            {children}
          </main>
          <Copyrights />
        </Providers>
      </body>
    </html>
  );
}
